license:
  name: lgpl
  version: 3
program:
  name: Evaluation-MIG
  description: Program for the evaluation of building incremental MIGs.
  authors: Sebastian Krieter
  url: https://github.com/skrieter/evaluation-mig
  year: 2021
